### ISSUE TITLE
Adicionem mais instruções do projeto no README!

### ISSUE THREAD

**Issue by danvitoriano** [onurbasfar/InvestiBot#6]
Muito bom o projeto de vocês! Achei muito útil ter isso como bot no Telegram!

Quero compartilhar o projeto de vocês no meu Twitter! Adicionem no README instruções sobre:
- [ ] como rodar o programa (inclua instruções sobre as tasks do Gradle)

Fico no aguardo! Respondam na issue!

Parabéns! 🚀

**Comment by bruno-vieira-farias** [comment]
Foi adicionado README as instruções para execução do projeto. Abraço.

**Comment by danvitoriano** [comment]
parabéns, ficou ótimo!
